# This workflow enables developers to call PR-Agents `/[actions]` in PR's comments and upon PR creation.
# Learn more at https://www.codium.ai/pr-agent/
# This is v0.2 of this workflow file

name: PR-Agent

on:
  # pull_request:
  # issue_comment:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: PR Agent action step 0
        id: pragent0
        uses: qodo-ai/pr-agent@v0.29

        
      - name: PR Agent action step
        id: pragent1
        uses: docker://codiumai/pr-agent:0.29-github_action # v0.29

      - name: PR Agent action step
        id: pragent2
        uses: docker://codiumai/pr-agent:0.29

      - name: PR Agent action step 2
        id: pragent3
        uses: docker://codiumai/pr-agent@sha256:bb70e388332d282794fe2e06745c338505108ff429a19f777ecb6931c28b0602 # v0.29
